MOTYWACYJNE_CYTATY = [
    "Nie poddawaj się, wielkie rzeczy potrzebują czasu.",
    "Sukces to suma małych wysiłków powtarzanych codziennie.",
    "Twoje marzenia są ważniejsze niż Twoje wymówki.",
    "Uwierz w siebie, a wszystko stanie się możliwe.",
    "Zmieniaj świat na lepsze każdego dnia.",
    "Nie ma rzeczy niemożliwych, są tylko trudne do osiągnięcia.",
    "Działaj z pasją, a sukces przyjdzie sam.",
    "Każdy dzień to nowa szansa, by zmienić swoje życie.",
    "Nie bój się zaczynać od nowa.",
    "Małe kroki prowadzą do wielkich zmian.",
    "Rób to, co kochasz, a nigdy nie będziesz musiał pracować.",
    "Wiara w siebie to pierwszy krok do sukcesu.",
    "Nie czekaj na idealny moment, zacznij teraz.",
    "Trudności są po to, by je pokonywać.",
    "Twoja przyszłość zaczyna się dziś, nie jutro.",
    "Wielkie marzenia wymagają wielkich działań.",
    "Nigdy nie rezygnuj z celu, nawet jeśli droga jest ciężka.",
    "Bądź wytrwały, a osiągniesz wszystko, co zaplanujesz.",
    "Zamiast marzyć, zacznij działać.",
    "Sukces jest w Twoich rękach.",
]